### ISSUE TITLE
Minimal Scrollbar now Broken on Latest Chrome Version 61.0.3163.91 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by jtbrown3** [iaarchiver/MinimalScrollbar#11]
Minimal Scrollbar now Broken on Latest Chrome Version 61.0.3163.91 (Official Build) (64-bit).
On ALL web pages now, the vertical scroll bar remains fixed and unmovable (auto-hide works but is useless).   PLEASE FIX, I LOVE THIS EXTENSION!!

**Comment by StickmansPub** [comment]
ETA when this will be fixed? I can't live without this mod D:

**Comment by Ryonez** [comment]
Author has been gone for over a year it seems.

**Comment by jtbrown3** [comment]
Personally, I'm going to stop using this extension and use the "Overlay Scrollbars" Chrome browser flag [chrome://flags/#overlay-scrollbars]. It looks pretty similar and means I won't have to use an abandoned extension.

**Comment by Ryonez** [comment]
IT doesn't autohide, and that's the thing I want the most :(

**Comment by jtbrown3** [comment]
The "Overlay Scrollbars" flag/feature autohides perfectly with my Chrome browser [Version 62.0.3202.62 (Official Build) 64-bit] on Windows 10...

**Comment by Ryonez** [comment]
Oh? Now this I have to try out. >.>
**Runs off.**

**Comment by Ryonez** [comment]
:o Awesome! Thank you for letting me know.

**Comment by jtbrown3** [comment]
Sure thing! :)

**Comment by charlesmagnuson** [comment]
I would love to give the "Overlay Scrollbars" flag a try, but after updating to v62.0.3202.62 (Mac) I do not see the option listed: http://ca.mag.cm/3r2f2k1W212d

I'm looking in the correct place, right?

**Comment by jtbrown3** [comment]
Sorry to report, @charlesmagnuson, But it looks like the experimental "Overlay Scrollbars" flag is currently limited to Windows, Linux, and Chrome OS (see screenclip).
![image](https://user-images.githubusercontent.com/634825/31979176-1c37de72-b8fa-11e7-8b91-95eb99644ef9.png)

**Comment by LeBaux** [comment]
Works in Vivaldi too. Open vivaldi://flags look for Overlay Scrollbars. This might render this extension obsolete, but I think @iaarchiver deserves a **big thank you** for making the extension that served for such a long time.

**Comment by iaarchiver** [comment]
Sorry for my late reply and merge. Please update v0.4, and check it works.
But, now I reccommend to use experimental "Overlay Scrollbars", too. 
Anyway, thanks for your support!

**Comment by ghost** [comment]
Oh boy! Thank you very much for the update. I really appreciate your help.

I'm unable to get the autohide feature to work on some websites such as washingtonpost.com, but it does work on other websites such as this one. Either way, this extension makes scrollbars much nicer in terms of appearance.

**Comment by jtbrown3** [comment]
@iaarchiver Thank you very much for your recent update and  _outstanding_ work on this great extension! :)
-JT
