### ISSUE TITLE
Does not autohide in youtube videos

### ISSUE THREAD

**Issue by AxlLind** [iaarchiver/MinimalScrollbar#17]
Looks like this isn't maintained anymore but this seems important since it's a problem with youtube.

With youtube's change to their player, where you can now "scroll down for details", the scrollbar will now show on the video.

**Comment by chris24hdez** [comment]
I can confirm this. I get the same in Chrome 73.0.3683.86
Should properly hide when full-screen mode is detected, but it doesn't.

**Comment by AxlLind** [comment]
No longer an issue after changes from youtube.
