### ISSUE TITLE
breaks trello.com and heroku.com

### ISSUE THREAD

**Issue by lacostej** [iaarchiver/MinimalScrollbar#3]
![screen shot 2015-08-30 at 13 58 37](https://cloud.githubusercontent.com/assets/24282/9567115/4ad012c8-4f1f-11e5-84bc-9d1ab35376b9.png)

**Comment by lacostej** [comment]
And also crowdin.com

**Comment by iaarchiver** [comment]
I'm sorry for late reply and fix.
You remind me that I fixed several bugs including this a year ago.
Please update v0.3.7, and check it works.

**Comment by iaarchiver** [comment]
But I couldn't reprocude bugs on crowdin.com. Could you tell me more details about it. (sorry for closing issue.)
